### ISSUE TITLE
COULDNT FIGURE OUT HOW TO MESSAGE YOU SO I MADE AN ISSUE

### ISSUE THREAD

**Issue by rolontloss** [DragonLegion/phpVhost#1]
Hey, Its me Kagome from chewynet. Where the fuck are you guys?

**Comment by chewyb13** [comment]
the basic email system still works Kagome, and the irc server went down and such, we've been trying to get it back up but meh.

**Comment by rolontloss** [comment]
I have a server still you are welcome to it  I have missed you guys

**Comment by rolontloss** [comment]
Oh hey
